### ISSUE TITLE
Can't compile on Ubuntu 22.04 (Jammy Jellyfish)

### ISSUE THREAD

**Issue by belovachap** [primecoin/primecoin#123]
```
> qmake
> make
...
src/base58.h:100:21: error: cannot convert ‘CBigNum*’ to ‘BIGNUM*’ {aka ‘bignum_st*’}
  100 |         if (!BN_mul(&bn, &bn, &bn58, pctx))
      |                     ^~~
      |                     |
      |                     CBigNum*
In file included from src/bignum.h:10,
                 from src/main.h:10,
                 from src/wallet.h:13,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:13:
```
